name: TruffleHog Scan

on:
  push:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Install TruffleHog
    #   run: |
    #     pip install trufflehog

    # - name: Run TruffleHog
    #   run: |
    #     trufflehog https://github.com/${{ github.repository }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TruffleHog
      run: |
        docker pull trufflesecurity/trufflehog:latest

    - name: Run TruffleHog
      run: |
        docker run --rm -v $PWD:/pwd trufflesecurity/trufflehog:latest github --repo https://github.com/${{ github.repository }}

