name: TruffleHog Scan

on:
  push:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Install TruffleHog
    #   run: |
    #     pip install trufflehog

    # - name: Run TruffleHog
    #   run: |
    #     trufflehog https://github.com/${{ github.repository }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TruffleHog
      run: |
        docker pull trufflesecurity/trufflehog:latest

    - name: Run TruffleHog
      id: trufflehog
      run: |
        output=$(docker run --rm -v $PWD:/pwd trufflesecurity/trufflehog:latest github --repo https://github.com/${{ github.repository }})
        echo "::set-output name=trufflehog_output::$output"

    - name: Check TruffleHog output
      run: |
        if [[ "${{ steps.trufflehog.outputs.trufflehog_output }}" == *"Found unverified result"* ]]; then
          echo "TruffleHog detected secrets. Failing the pipeline."

          secret_info=$(echo "$trufflehog_output" | grep -E "Commit:|Email:|File:|Line:|Link:|Repository:")

      
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/camilafernanda/tests-CI-VollMed/issues \
            -d "{\"title\":\"Found a secret\",\"body\":\"TruffleHog detected a secret:\n$secret_info\",\"labels\":[\"bug\"]}"

          exit 1
        fi